# Generated by Django 5.2.17 on 2026-09-07 13:11

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('TENANT', 'Tenant / Roommate'), ('LANDLORD', 'Landlord / Property Owner'), ('ADMIN', 'Platform Administrator')], default='TENANT', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='landlord_docs/')),
                ('response_time_minutes', models.PositiveIntegerField(default=60)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('occupation_status', models.CharField(blank=True, max_length=100)),
                ('university_or_company', models.CharField(blank=True, max_length=150)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('min_budget', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('preferred_move_in_date', models.DateField(blank=True, null=True)),
                ('bedrooms_preferred', models.PositiveSmallIntegerField(default=1)),
                ('furnishing_preference', models.CharField(choices=[('FURNISHED', 'Furnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('UNFURNISHED', 'Unfurnished'), ('ANY', 'Any')], default='ANY', max_length=30)),
                ('lifestyle_type', models.CharField(choices=[('QUIET', 'Quiet & Studious'), ('SOCIAL', 'Social & Outgoing'), ('FLEXIBLE', 'Flexible & Balanced')], default='FLEXIBLE', max_length=30)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('smoking_preference', models.BooleanField(default=False)),
                ('cleanliness_level', models.CharField(choices=[('VERY_CLEAN', 'Very Clean'), ('MODERATE', 'Moderately Clean'), ('RELAXED', 'Relaxed')], default='MODERATE', max_length=30)),
                ('sleep_schedule', models.CharField(choices=[('EARLY_BIRD', 'Early Bird'), ('NIGHT_OWL', 'Night Owl'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('is_onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
