# Generated by Django 5.2.17 on 2026-09-07 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_property_available_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries & Food'), ('UTILITIES', 'Water & Electricity'), ('INTERNET', 'WiFi / Internet'), ('HOUSEHOLD', 'Cleaning & Household'), ('ENTERTAINMENT', 'Entertainment & Outings'), ('OTHER', 'Other')], default='GROCERIES', max_length=30)),
                ('split_type', models.CharField(choices=[('EQUAL', 'Split Equally'), ('EXACT', 'Exact Amounts'), ('PERCENTAGE', 'By Percentage')], default='EQUAL', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.property')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], default='ESEWA', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expense', 'user')},
            },
        ),
    ]
