from django.core.management.base import BaseCommand
from apps.users.models import User
from apps.properties.models import Property, PropertyImage


class Command(BaseCommand):
    help = 'Seeds Kathmandu Valley rental properties for RoomMateHub'

    def handle(self, *args, **options):
        landlord = User.objects.filter(role=User.Role.LANDLORD).first()
        if not landlord:
            self.stdout.write(self.style.ERROR('No landlord user found. Run create_demo_users first.'))
            return

        properties_data = [
            {
                'title': 'Modern 2BHK Apartment with Private Balcony',
                'description': 'Bright and airy 2BHK apartment situated in peaceful Shantinagar, New Baneshwor. Features parquet flooring, 24-hour deep-well water supply, modular kitchen with chimney, and a sunny private balcony facing southwest. Ideal for university students or young IT professionals.',
                'property_type': Property.PropertyType.APARTMENT,
                'address': 'Shantinagar Gate No. 2, New Baneshwor',
                'area': 'Baneshwor',
                'city': 'Kathmandu',
                'latitude': 27.691520,
                'longitude': 85.341520,
                'monthly_rent': 25000,
                'security_deposit': 25000,
                'bedrooms': 2,
                'bathrooms': 1,
                'floor': 3,
                'area_sqft': 750,
                'furnishing': Property.Furnishing.FURNISHED,
                'has_wifi': True,
                'has_parking': True,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': True,
                'has_balcony': True,
                'has_elevator': False,
                'pets_allowed': False,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': True,
                'rating': 4.9,
                'total_reviews': 18,
                'images': [
                    'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Sunny Studio Flat near Pulchowk Campus',
                'description': 'Newly renovated compact studio apartment just a 5-minute walk from IOE Pulchowk Engineering Campus. Fully equipped with dedicated study workspace, high-speed 100Mbps fiber internet, solar hot water, and independent access.',
                'property_type': Property.PropertyType.STUDIO,
                'address': 'Behind St. Xavier’s College, Kupondole Height',
                'area': 'Kupondole',
                'city': 'Lalitpur',
                'latitude': 27.689100,
                'longitude': 85.314200,
                'monthly_rent': 16000,
                'security_deposit': 16000,
                'bedrooms': 1,
                'bathrooms': 1,
                'floor': 2,
                'area_sqft': 420,
                'furnishing': Property.Furnishing.FURNISHED,
                'has_wifi': True,
                'has_parking': True,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': False,
                'has_balcony': False,
                'has_elevator': False,
                'pets_allowed': True,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': True,
                'rating': 4.8,
                'total_reviews': 24,
                'images': [
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Spacious 3BHK Shared Penthouse in Restaurant Hub',
                'description': 'High-end 3-bedroom penthouse in the culinary and expatriate district of Jhamsikhel. Panoramic rooftop views of the Kathmandu valley, private gym corner, master bedroom with ensuite jacuzzi, and dedicated underground car parking.',
                'property_type': Property.PropertyType.PENTHOUSE,
                'address': 'Jhamsikhel Road, Near Moksh',
                'area': 'Jhamsikhel',
                'city': 'Lalitpur',
                'latitude': 27.682100,
                'longitude': 85.308200,
                'monthly_rent': 45000,
                'security_deposit': 45000,
                'bedrooms': 3,
                'bathrooms': 2,
                'floor': 4,
                'area_sqft': 1350,
                'furnishing': Property.Furnishing.FURNISHED,
                'has_wifi': True,
                'has_parking': True,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': True,
                'has_balcony': True,
                'has_elevator': True,
                'pets_allowed': True,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': True,
                'rating': 4.9,
                'total_reviews': 12,
                'images': [
                    'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Cozy Private Room in Shared Student Flat',
                'description': 'Single fully furnished bedroom inside a friendly 3BHK flat shared with two final year engineering students. Rent includes electricity, water, and 100Mbps Wi-Fi. Common living room and large kitchen.',
                'property_type': Property.PropertyType.ROOM,
                'address': 'Patan Dhoka Chowk, Lalitpur',
                'area': 'Patan',
                'city': 'Lalitpur',
                'latitude': 27.677500,
                'longitude': 85.317000,
                'monthly_rent': 10000,
                'security_deposit': 10000,
                'bedrooms': 1,
                'bathrooms': 1,
                'floor': 2,
                'area_sqft': 220,
                'furnishing': Property.Furnishing.FURNISHED,
                'has_wifi': True,
                'has_parking': True,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': True,
                'has_balcony': False,
                'has_elevator': False,
                'pets_allowed': False,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': False,
                'rating': 4.7,
                'total_reviews': 8,
                'images': [
                    'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Traditional Newari Style 2BHK House Portion',
                'description': 'Experience traditional heritage architecture combined with modern comfort in historical Patan. Exposed red brick walls, wooden carved windows, modern modular bathroom, and cozy courtyard garden.',
                'property_type': Property.PropertyType.FLAT,
                'address': 'Near Mangal Bazaar, Patan',
                'area': 'Patan',
                'city': 'Lalitpur',
                'latitude': 27.674000,
                'longitude': 85.325000,
                'monthly_rent': 22000,
                'security_deposit': 22000,
                'bedrooms': 2,
                'bathrooms': 1,
                'floor': 1,
                'area_sqft': 680,
                'furnishing': Property.Furnishing.SEMI_FURNISHED,
                'has_wifi': True,
                'has_parking': False,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': False,
                'has_balcony': True,
                'has_elevator': False,
                'pets_allowed': True,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': False,
                'rating': 4.8,
                'total_reviews': 16,
                'images': [
                    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Premium 2BHK Apartment with Rooftop Solar',
                'description': 'Executive level flat near diplomatic missions and embassies in Baluwatar. Features Italian marble counter tops, video door phone, 24-hour guarded security, CCTV surveillance, and reserved basement car parking.',
                'property_type': Property.PropertyType.APARTMENT,
                'address': 'Baluwatar Main Road, Near PM Residence',
                'area': 'Baluwatar',
                'city': 'Kathmandu',
                'latitude': 27.728500,
                'longitude': 85.331200,
                'monthly_rent': 35000,
                'security_deposit': 50000,
                'bedrooms': 2,
                'bathrooms': 2,
                'floor': 2,
                'area_sqft': 900,
                'furnishing': Property.Furnishing.FURNISHED,
                'has_wifi': True,
                'has_parking': True,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': True,
                'has_balcony': True,
                'has_elevator': True,
                'has_cctv': True,
                'pets_allowed': False,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': True,
                'rating': 5.0,
                'total_reviews': 31,
                'images': [
                    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Affordable 1BHK Flat in Quiet Residential Block',
                'description': 'Clean, peaceful 1BHK ground-floor flat with separate kitchen, large bedroom, and attached bathroom. Constant municipal and tanker water with deep filtering. Perfect for single students or working couples.',
                'property_type': Property.PropertyType.FLAT,
                'address': 'Balkumari Ring Road, Koteshwor',
                'area': 'Koteshwor',
                'city': 'Kathmandu',
                'latitude': 27.675000,
                'longitude': 85.348000,
                'monthly_rent': 14000,
                'security_deposit': 14000,
                'bedrooms': 1,
                'bathrooms': 1,
                'floor': 1,
                'area_sqft': 480,
                'furnishing': Property.Furnishing.UNFURNISHED,
                'has_wifi': True,
                'has_parking': True,
                'has_24h_water': True,
                'has_electricity_backup': False,
                'has_kitchen': True,
                'has_washing_machine': False,
                'has_balcony': False,
                'has_elevator': False,
                'pets_allowed': True,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': False,
                'rating': 4.6,
                'total_reviews': 7,
                'images': [
                    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1000&auto=format&fit=crop&q=80',
                ]
            },
            {
                'title': 'Historic Townhouse near Bhaktapur Durbar Square',
                'description': 'Unique cultural experience in the heart of Bhaktapur. Beautiful rooftop view of Nyatapola temple and Changu Narayan ridge. Walking distance to markets, cafes, and historical attractions.',
                'property_type': Property.PropertyType.HOUSE,
                'address': 'Taumadhi Square, Bhaktapur',
                'area': 'Bhaktapur',
                'city': 'Bhaktapur',
                'latitude': 27.672000,
                'longitude': 85.428000,
                'monthly_rent': 28000,
                'security_deposit': 28000,
                'bedrooms': 3,
                'bathrooms': 2,
                'floor': 3,
                'area_sqft': 1100,
                'furnishing': Property.Furnishing.SEMI_FURNISHED,
                'has_wifi': True,
                'has_parking': False,
                'has_24h_water': True,
                'has_electricity_backup': True,
                'has_kitchen': True,
                'has_washing_machine': True,
                'has_balcony': True,
                'has_elevator': False,
                'pets_allowed': False,
                'smoking_allowed': False,
                'is_verified': True,
                'is_featured': False,
                'rating': 4.9,
                'total_reviews': 19,
                'images': [
                    'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=1000&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1000&auto=format&fit=crop&q=80',
                ]
            },
        ]

        created_count = 0
        for pdata in properties_data:
            images = pdata.pop('images', [])
            title = pdata['title']
            prop, created = Property.objects.get_or_create(
                title=title,
                defaults={'landlord': landlord, **pdata},
            )
            for i, img_url in enumerate(images):
                image, _ = PropertyImage.objects.get_or_create(
                    property=prop,
                    order=i,
                    defaults={'image_url': img_url, 'is_primary': i == 0},
                )
                if i == 0 and image.image_url != img_url:
                    image.image_url = img_url
                    image.is_primary = True
                    image.save(update_fields=['image_url', 'is_primary'])
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created_count} properties.'))
