# Generated by Django 5.2.17 on 2026-09-07 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('FLAT', 'Flat'), ('ROOM', 'Private Room'), ('HOUSE', 'House'), ('PENTHOUSE', 'Penthouse')], default='APARTMENT', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(default='Kathmandu', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=27.717242, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=85.32396, max_digits=9)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilities_included', models.JSONField(blank=True, default=list)),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_stay_months', models.PositiveSmallIntegerField(default=6)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('area_sqft', models.PositiveIntegerField(default=600)),
                ('furnishing', models.CharField(choices=[('FURNISHED', 'Furnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('UNFURNISHED', 'Unfurnished')], default='FURNISHED', max_length=30)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=True)),
                ('has_24h_water', models.BooleanField(default=True)),
                ('has_electricity_backup', models.BooleanField(default=True)),
                ('has_kitchen', models.BooleanField(default=True)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('gender_preference', models.CharField(choices=[('ANY', 'Any Gender'), ('FEMALE_ONLY', 'Female Only'), ('MALE_ONLY', 'Male Only')], default='ANY', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('RENTED', 'Rented'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
