# Generated by Django 5.2.17 on 2026-09-07 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
