# Generated by Django 5.2.17 on 2026-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
