# Generated by Django 5.2.17 on 2026-09-07 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_property_available_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, help_text='e.g. Room 201 or Entire Flat', max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month when rent is due (1-31)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Tenancy'), ('TERMINATED', 'Terminated'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Commencement')], default='ACTIVE', max_length=20)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month_for', models.CharField(help_text='e.g. September 2026 / Ashwin 2083', max_length=50)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('BANK_TRANSFER', 'ConnectIPS / Bank Transfer'), ('CASH', 'Cash'), ('SIMULATED', 'Simulated Digital Payment')], default='SIMULATED', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.lease')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
