import React, { useState, useEffect } from 'react';
import {
  FileText,
  CheckCircle2,
  Clock,
  Printer,
  X,
  Loader2,
  PenTool,
} from 'lucide-react';
import {
  agreementService,
  type RentalAgreement,
} from '../../services/agreementService';

interface AgreementViewerModalProps {
  isOpen: boolean;
  onClose: () => void;
  userRole?: string;
}

export const AgreementViewerModal: React.FC<AgreementViewerModalProps> = ({
  isOpen,
  onClose,
  userRole: _userRole = 'TENANT',
}) => {
  const [selectedAgr, setSelectedAgr] = useState<RentalAgreement | null>(null);
  const [loading, setLoading] = useState(true);

  // Signing state
  const [signatureName, setSignatureName] = useState('');
  const [signing, setSigning] = useState(false);

  useEffect(() => {
    if (isOpen) {
      loadAgreements();
    }
  }, [isOpen]);

  const loadAgreements = async () => {
    setLoading(true);
    try {
      const data = await agreementService.getAgreements();
      if (data.length > 0) {
        setSelectedAgr(data[0]);
      }
    } catch (err) {
      console.error('Failed to load agreements', err);
    } finally {
      setLoading(false);
    }
  };

  const handleSign = async () => {
    if (!selectedAgr || !signatureName.trim() || signing) return;

    setSigning(true);
    try {
      await agreementService.signAgreement(selectedAgr.id, signatureName.trim());
      setSignatureName('');
      loadAgreements();
    } catch (err) {
      alert('Failed to sign agreement.');
    } finally {
      setSigning(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
      <div className="relative w-full max-w-4xl h-[90vh] bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-lg text-slate-900 dark:text-white">
                Legal Tenancy Lease Agreement
              </h3>
              <p className="text-xs text-slate-500">
                Governed by National Civil (Code) Act, 2074 (Nepal)
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {selectedAgr && (
              <a
                href={agreementService.getHtmlUrl(selectedAgr.id)}
                target="_blank"
                rel="noreferrer"
                className="px-3 py-1.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-bold transition flex items-center gap-1.5"
              >
                <Printer className="w-3.5 h-3.5" /> Print / PDF
              </a>
            )}
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Body */}
        {loading ? (
          <div className="flex-1 flex flex-col items-center justify-center text-slate-400 gap-2">
            <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
            <p className="text-sm">Loading legal agreement...</p>
          </div>
        ) : !selectedAgr ? (
          <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
            <FileText className="w-12 h-12 text-slate-300 mb-2" />
            <p className="font-bold text-slate-700 dark:text-slate-300">No Rental Agreement Available</p>
            <p className="text-xs text-slate-500 mt-1">Agreements generated by your landlord will appear here for signing.</p>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {/* Agreement Metadata Card */}
            <div className="p-6 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <span
                    className={`px-3 py-1 rounded-full text-xs font-bold border ${
                      selectedAgr.status === 'EXECUTED'
                        ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-400 border-emerald-300'
                        : 'bg-amber-100 text-amber-800 dark:bg-amber-950/40 dark:text-amber-400 border-amber-300'
                    }`}
                  >
                    {selectedAgr.status === 'EXECUTED' ? 'Fully Executed & Legally Binding' : 'Awaiting Signatures'}
                  </span>
                  <h2 className="text-xl font-extrabold text-slate-900 dark:text-white mt-2">
                    {selectedAgr.title}
                  </h2>
                </div>
                <div className="text-right">
                  <span className="text-xs text-slate-400 block">Monthly Rent</span>
                  <span className="text-lg font-black text-indigo-600 dark:text-indigo-400">
                    NPR {Number(selectedAgr.monthly_rent).toLocaleString()}
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs pt-3 border-t border-slate-200/60 dark:border-slate-700/60">
                <div>
                  <span className="text-slate-400 block">Landlord</span>
                  <strong className="text-slate-900 dark:text-white">{selectedAgr.landlord?.full_name}</strong>
                </div>
                <div>
                  <span className="text-slate-400 block">Tenant</span>
                  <strong className="text-slate-900 dark:text-white">{selectedAgr.tenant?.full_name}</strong>
                </div>
                <div>
                  <span className="text-slate-400 block">Security Deposit</span>
                  <strong className="text-slate-900 dark:text-white">NPR {Number(selectedAgr.security_deposit).toLocaleString()}</strong>
                </div>
                <div>
                  <span className="text-slate-400 block">Term Duration</span>
                  <strong className="text-slate-900 dark:text-white">{selectedAgr.start_date} to {selectedAgr.end_date}</strong>
                </div>
              </div>
            </div>

            {/* Clauses List */}
            <div className="space-y-4">
              <h4 className="font-bold text-sm text-slate-900 dark:text-white uppercase tracking-wider">
                Standard Tenancy Clauses & By-Laws
              </h4>
              <div className="space-y-3">
                {selectedAgr.terms_clauses?.map((c) => (
                  <div
                    key={c.clause_number}
                    className="p-4 rounded-xl border border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-1"
                  >
                    <h5 className="font-bold text-xs text-slate-900 dark:text-white">
                      {c.clause_number}. {c.title}
                    </h5>
                    <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">{c.body}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Signatures Status Box */}
            <div className="p-6 rounded-2xl bg-indigo-50/50 dark:bg-indigo-950/20 border border-indigo-200/60 dark:border-indigo-900/40 space-y-4">
              <h4 className="font-bold text-xs uppercase tracking-wider text-indigo-900 dark:text-indigo-300">
                Digital Signatures Status
              </h4>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Landlord Signature */}
                <div className="p-4 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-slate-500">First Party (Landlord)</span>
                    {selectedAgr.landlord_signed ? (
                      <span className="text-xs text-emerald-600 font-bold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Verified Signed
                      </span>
                    ) : (
                      <span className="text-xs text-amber-500 font-bold flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5" /> Pending
                      </span>
                    )}
                  </div>
                  {selectedAgr.landlord_signed ? (
                    <div>
                      <p className="font-serif italic text-lg text-indigo-600">{selectedAgr.landlord_signature_data}</p>
                      <span className="text-[10px] text-slate-400">
                        {new Date(selectedAgr.landlord_signed_at || '').toLocaleString()}
                      </span>
                    </div>
                  ) : (
                    <p className="text-xs text-slate-400 italic">Awaiting signature...</p>
                  )}
                </div>

                {/* Tenant Signature */}
                <div className="p-4 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-slate-500">Second Party (Tenant)</span>
                    {selectedAgr.tenant_signed ? (
                      <span className="text-xs text-emerald-600 font-bold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Verified Signed
                      </span>
                    ) : (
                      <span className="text-xs text-amber-500 font-bold flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5" /> Pending
                      </span>
                    )}
                  </div>
                  {selectedAgr.tenant_signed ? (
                    <div>
                      <p className="font-serif italic text-lg text-indigo-600">{selectedAgr.tenant_signature_data}</p>
                      <span className="text-[10px] text-slate-400">
                        {new Date(selectedAgr.tenant_signed_at || '').toLocaleString()}
                      </span>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      <input
                        type="text"
                        placeholder="Type full legal name to sign..."
                        value={signatureName}
                        onChange={(e) => setSignatureName(e.target.value)}
                        className="w-full px-3 py-1.5 text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white"
                      />
                      <button
                        onClick={handleSign}
                        disabled={!signatureName.trim() || signing}
                        className="w-full py-1.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition flex items-center justify-center gap-1.5"
                      >
                        {signing ? <Loader2 className="w-3 h-3 animate-spin" /> : <PenTool className="w-3 h-3" />}
                        Digitally Sign Agreement
                      </button>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
