# Generated by Django 5.2.17 on 2026-09-07 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_property_available_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('move_in_date', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed (Full-Time)'), ('PART_TIME', 'Employed (Part-Time)'), ('SELF_EMPLOYED', 'Self-Employed / Freelancer'), ('STUDENT', 'Student'), ('UNEMPLOYED', 'Unemployed'), ('OTHER', 'Other')], default='EMPLOYED', max_length=30)),
                ('credit_score_range', models.CharField(choices=[('EXCELLENT', 'Excellent (750+)'), ('GOOD', 'Good (700-749)'), ('FAIR', 'Fair (650-699)'), ('POOR', 'Below 650'), ('NA', 'Not Applicable / Student')], default='NA', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Cover message to landlord')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('guarantor_name', models.CharField(blank=True, max_length=100)),
                ('guarantor_contact', models.CharField(blank=True, max_length=50)),
                ('landlord_notes', models.TextField(blank=True, help_text='Private notes for landlord')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='application_tenant__9a42d2_idx'), models.Index(fields=['property', 'status'], name='application_propert_f0954e_idx')],
            },
        ),
    ]
